package main.java.tests;

import ec.gp.GPIndividual;
import ec.gp.GPNode;
import ec.gp.GPTree;
import main.java.actions.operators.SequenceOperator;
import main.java.main.OmnetStateData;
import main.java.omnet.tactics.DecreaseDimmerLevelC;
import main.java.omnet.tactics.DecreaseTrafficLevelB;
import main.java.omnet.tactics.DecreaseTrafficLevelF;
import main.java.omnet.tactics.IncreaseDimmerLevelA;
import main.java.omnet.tactics.IncreaseTrafficLevelA;
import main.java.omnet.tactics.IncreaseTrafficLevelB;
import main.java.omnet.tactics.IncreaseTrafficLevelD;
import main.java.omnet.tactics.ShutdownServerC;
import main.java.omnet.tactics.StartNewServerB;

public class TestSize16 {
	public static void build16(GPIndividual ind){
		GPTree[] treeInit = {new GPTree()};
		ind.trees = treeInit;
		GPNode node1 = new SequenceOperator();
		GPNode node2 = new SequenceOperator();
		GPNode node3 = new SequenceOperator();
		GPNode node4 = new SequenceOperator();
		GPNode node5 = new SequenceOperator();
		GPNode node6 = new SequenceOperator();
		GPNode node7 = new SequenceOperator();
		GPNode node8 = new SequenceOperator();
		GPNode node9 = new SequenceOperator();
		GPNode node10 = new SequenceOperator();
		GPNode node11 = new SequenceOperator();
		GPNode node12 = new SequenceOperator();
		GPNode node13 = new SequenceOperator();
		GPNode node14 = new SequenceOperator();
		GPNode node15 = new SequenceOperator();
		GPNode node16 = new IncreaseDimmerLevelA();
		GPNode node17 = new IncreaseDimmerLevelA();
		GPNode node18 = new StartNewServerB();
		GPNode node19 = new IncreaseTrafficLevelD();
		GPNode node20 = new DecreaseTrafficLevelF();
		GPNode node21 = new IncreaseTrafficLevelD();
		GPNode node22 = new IncreaseTrafficLevelD();
		GPNode node23 = new IncreaseTrafficLevelD();
		GPNode node24 = new IncreaseTrafficLevelD();
		GPNode node25 = new IncreaseTrafficLevelB();
		GPNode node26 = new DecreaseTrafficLevelB();
		GPNode node27 = new IncreaseTrafficLevelD();
		GPNode node28 = new DecreaseDimmerLevelC();
		GPNode node29 = new IncreaseTrafficLevelA();
		GPNode node30 = new IncreaseTrafficLevelA();
		GPNode node31 = new ShutdownServerC();

		GPNode[] childrenOfNode1 = new GPNode[2];
		GPNode[] childrenOfNode2 = new GPNode[2];
		GPNode[] childrenOfNode3 = new GPNode[2];
		GPNode[] childrenOfNode4 = new GPNode[2];
		GPNode[] childrenOfNode5 = new GPNode[2];
		GPNode[] childrenOfNode6 = new GPNode[2];
		GPNode[] childrenOfNode7 = new GPNode[2];
		GPNode[] childrenOfNode8 = new GPNode[2];
		GPNode[] childrenOfNode9 = new GPNode[2];
		GPNode[] childrenOfNode10 = new GPNode[2];
		GPNode[] childrenOfNode11 = new GPNode[2];
		GPNode[] childrenOfNode12 = new GPNode[2];
		GPNode[] childrenOfNode13 = new GPNode[2];
		GPNode[] childrenOfNode14 = new GPNode[2];
		GPNode[] childrenOfNode15 = new GPNode[2];
		GPNode[] childrenOfNode16 = new GPNode[0];
		GPNode[] childrenOfNode17 = new GPNode[0];
		GPNode[] childrenOfNode18 = new GPNode[0];
		GPNode[] childrenOfNode19 = new GPNode[0];
		GPNode[] childrenOfNode20 = new GPNode[0];
		GPNode[] childrenOfNode21 = new GPNode[0];
		GPNode[] childrenOfNode22 = new GPNode[0];
		GPNode[] childrenOfNode23 = new GPNode[0];
		GPNode[] childrenOfNode24 = new GPNode[0];
		GPNode[] childrenOfNode25 = new GPNode[0];
		GPNode[] childrenOfNode26 = new GPNode[0];
		GPNode[] childrenOfNode27 = new GPNode[0];
		GPNode[] childrenOfNode28 = new GPNode[0];
		GPNode[] childrenOfNode29 = new GPNode[0];
		GPNode[] childrenOfNode30 = new GPNode[0];
		GPNode[] childrenOfNode31 = new GPNode[0];

		childrenOfNode1[0] = node2;
		childrenOfNode1[1] = node3;
		childrenOfNode2[0] = node4;
		childrenOfNode2[1] = node5;
		childrenOfNode3[0] = node6;
		childrenOfNode3[1] = node7;
		childrenOfNode4[0] = node8;
		childrenOfNode4[1] = node9;
		childrenOfNode5[0] = node10;
		childrenOfNode5[1] = node11;
		childrenOfNode6[0] = node12;
		childrenOfNode6[1] = node13;
		childrenOfNode7[0] = node14;
		childrenOfNode7[1] = node15;
		childrenOfNode8[0] = node16;
		childrenOfNode8[1] = node17;
		childrenOfNode9[0] = node18;
		childrenOfNode9[1] = node19;
		childrenOfNode10[0] = node20;
		childrenOfNode10[1] = node21;
		childrenOfNode11[0] = node22;
		childrenOfNode11[1] = node23;
		childrenOfNode12[0] = node24;
		childrenOfNode12[1] = node25;
		childrenOfNode13[0] = node26;
		childrenOfNode13[1] = node27;
		childrenOfNode14[0] = node28;
		childrenOfNode14[1] = node29;
		childrenOfNode15[0] = node30;
		childrenOfNode15[1] = node31;


		ind.trees[0].child=node1;
		node1.children = childrenOfNode1;
		node2.children = childrenOfNode2;
		node3.children = childrenOfNode3;
		node4.children = childrenOfNode4;
		node5.children = childrenOfNode5;
		node6.children = childrenOfNode6;
		node7.children = childrenOfNode7;
		node8.children = childrenOfNode8;
		node9.children = childrenOfNode9;
		node10.children = childrenOfNode10;
		node11.children = childrenOfNode11;
		node12.children = childrenOfNode12;
		node13.children = childrenOfNode13;
		node14.children = childrenOfNode14;
		node15.children = childrenOfNode15;
		node16.children = childrenOfNode16;
		node17.children = childrenOfNode17;
		node18.children = childrenOfNode18;
		node19.children = childrenOfNode19;
		node20.children = childrenOfNode20;
		node21.children = childrenOfNode21;
		node22.children = childrenOfNode22;
		node23.children = childrenOfNode23;
		node24.children = childrenOfNode24;
		node25.children = childrenOfNode25;
		node26.children = childrenOfNode26;
		node27.children = childrenOfNode27;
		node28.children = childrenOfNode28;
		node29.children = childrenOfNode29;
		node30.children = childrenOfNode30;
		node31.children = childrenOfNode31;
	}
	
	public static void main(String[] args) throws InstantiationException{	

		OmnetStateData sd = new OmnetStateData();
		GPIndividual ind = new GPIndividual();
		build16(ind);
		sd.getAllFinalStates(ind.trees[0].child);
		sd.printScores();

	}
}
