package bullseye.tactics;

public enum AttackTactics {
	PHISH_VENDOR, PHISH_EMPLOYEE, ZERODAY_WEB, ZERODAY_PAYMENT,
	CRACK_WEB_HASHES, INFECT_POS, KEYLOG_WEB, KEYLOG_PAYMENT,
	EXFIL_DATA, DISRUPT_WEB, DISRUPT_PAYMENT, DISRUPT_POS;
}
